# Generated by Django 3.1.7 on 2021-09-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('custid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('custname', models.CharField(max_length=30)),
                ('custimage', models.CharField(max_length=300)),
                ('custemail', models.EmailField(max_length=100)),
                ('custpassword', models.CharField(max_length=30)),
            ],
        ),
    ]
