# Generated by Django 3.1.7 on 2021-09-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efarma', '0002_auto_20210912_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='proId',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
