# Generated by Django 3.1.7 on 2021-09-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efarma', '0003_auto_20210912_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='proDiscription',
            field=models.CharField(max_length=500),
        ),
    ]
