# Generated by Django 3.1.7 on 2021-09-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efarma', '0005_auto_20210912_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='proImage',
            field=models.ImageField(upload_to=''),
        ),
    ]
