# Generated by Django 3.1.7 on 2021-09-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efarma', '0008_auto_20210914_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='proImage',
            field=models.CharField(max_length=500),
        ),
    ]
