# Generated by Django 3.1.7 on 2021-09-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efarma', '0009_auto_20210914_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='proImage',
            field=models.ImageField(upload_to='Images/'),
        ),
    ]
