# Generated by Django 3.1.7 on 2021-09-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efarma', '0010_auto_20210914_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productss',
            fields=[
                ('proId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('proName', models.CharField(max_length=50)),
                ('proDiscription', models.CharField(max_length=600)),
                ('proImage', models.ImageField(upload_to='Images/')),
                ('proCompany', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('proCategory', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
