# Generated by Django 3.1.7 on 2021-09-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efarma', '0011_auto_20210915_0023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productss',
            new_name='Products',
        ),
    ]
