# Generated by Django 3.1.7 on 2021-09-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efarma', '0012_auto_20210915_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='proCategory',
        ),
        migrations.RemoveField(
            model_name='products',
            name='proCompany',
        ),
        migrations.RemoveField(
            model_name='products',
            name='proDiscription',
        ),
        migrations.RemoveField(
            model_name='products',
            name='proId',
        ),
        migrations.RemoveField(
            model_name='products',
            name='proImage',
        ),
        migrations.RemoveField(
            model_name='products',
            name='proName',
        ),
        migrations.AddField(
            model_name='products',
            name='productCategory',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='productCompany',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='productDiscription',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='products',
            name='productId',
            field=models.CharField(default='False', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='products',
            name='productImage',
            field=models.ImageField(null='False', upload_to='Images/'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='products',
            name='productName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
