# Generated by Django 3.1.7 on 2021-09-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efarma', '0014_auto_20210915_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productImage',
            field=models.ImageField(null='False', upload_to='Images/'),
        ),
    ]
