# Generated by Django 3.1.7 on 2021-09-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efarma', '0016_auto_20210920_2329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
