# Generated by Django 3.1.7 on 2021-09-20 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('efarma', '0019_auto_20210921_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='custid',
        ),
        migrations.AddField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
