# Generated by Django 3.1.7 on 2021-09-20 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efarma', '0021_auto_20210921_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='link',
            new_name='link_id',
        ),
    ]
