# Generated by Django 3.1.7 on 2021-09-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efarma', '0024_customer_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerImage',
            field=models.ImageField(null='False', upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='productImage',
            field=models.ImageField(null='False', upload_to='Images/'),
        ),
    ]
